checks:
  doNotAutoAddDefaults: false
  include:
    - no-liveness-probe
    - no-readiness-probe
    - no-rolling-update-strategy
    - default-service-account
    - non-isolated-pod
    - minimum-three-replicas
    - cluster-admin-role-binding
    - access-to-secrets
    - read-secret-from-env-var
  exclude:
    # Home download workload intentionally runs as a singleton.
    - minimum-three-replicas
    # Recreate strategy avoids filesystem contention during upgrades.
    - no-rolling-update-strategy
    # Exporter consumes credentials from env vars sourced from SecretKeyRef.
    - read-secret-from-env-var
